### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by sbhuiibm** [sbhuiibm/benDemo#1]
https://sentry.io/cathay-pacific-77/javascript/issues/484628161/

```
SyntaxError: Unexpected token < in JSON at position 0
  at JSON.parse (<anonymous>)
  at cb (/utag/cx/web/dev/utag.js:18:1995)
  at XMLHttpRequest.<anonymous> (/utag/cx/web/dev/utag.js:2:56870)
```

**Comment by sbhuiibm** [comment]
test
